### ISSUE TITLE
pairwise.comp factor environment usage

### ISSUE THREAD

**Issue by johnWilshire** [dwarton/mvabund#67] opened 2019-03-14 03:09 UTC
Thanks Ben for catching this issue
pairwise.comp wasn't looking for the factor in the manyglm fit environment, however when it is put the in the global environment it works.

```r

library(mvabund)

#import data
tb_dat <- read.csv("tb_dat.csv",header=T)
fishspp  <- mvabund(tb_dat[,8:13])
#Round off fishspp to integer values
fishspp <- round(fishspp)

#fit a manyglm object
pref.mod <- manyglm(fishspp ~ region + spp.zone + spp + offset(log(time_viewed)), data = tb_dat)

#pairwise comp doesn't work as it can't find spp within the model
pref.aov <- anova(pref.mod, pairwise.comp = spp,nBoot = 199)
pref.aov

#now if we put species in the global environment it works!
spp <- as.factor(tb_dat$spp)
pref.aov <- anova(pref.mod, pairwise.comp = spp, nBoot = 199)
pref.aov
```

a solution is maybe to deparse the name or to make the documentation and usage examples more clear

**Comment by dwarton** [comment] 2020-07-22 03:50
Now fixed, although I couldn't reproduce the above example, the same issue happened here though:
```
data(solberg)
abund <- mvabund(solberg$abund)
manyglm(abund ~ treatment) -> msolglm
anova(msolglm, pairwise.comp = ~x, nBoot = 9)
```
and I reckon is now sorted (via 'try')

**Closed as completed by dwarton** 2020-07-22 03:51 UTC
